version: '3'

services:
  calculateinterest:
    image: calculate-interest-image
    build:
      context: .
    ports:
      - 8080:80
    networks:
      - "local-network"

  interestrate:
    image: interest-rate-image
    build:
      context: .
    ports:
      - 8081:80
    networks:
      - "local-network"

networks: 
  local-network:
      driver: bridge